### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by alexandru-tetelea** [leijou/php-server#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [php-server](https://github.com/leijou/php-server) package, v0.3.0
### Stack Trace

Uncaught TypeError: path must be a string

```
At ATOM_SHELL_ASAR.js:50

TypeError: path must be a string
  at TypeError (native)
  at fs.lstatSync (fs.js:797:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at Object.module.exports.start (C:\Users\Alexandru\.atom\packages\php-server\lib\php-server.coffee:47:12)
  at atom-workspace.<anonymous> (C:\Users\Alexandru\.atom\packages\php-server\lib\php-server.coffee:27:65)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
  at C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:246:29)
  at C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Alexandru\AppData\Local\atom\app-0.187.0\resources\app\src\window-event-handler.js:182:20)

```
### Commands

```
     -1:12.7 core:confirm (atom-text-editor.editor.mini)
  3x -0:44.0 core:backspace (atom-text-editor.editor.mini)
  2x -0:43.2 core:confirm (atom-text-editor.editor.mini)
     -0:26.4 core:backspace (atom-text-editor.editor.mini)
     -0:23.3 core:confirm (atom-text-editor.editor.mini)
     -0:07.4 command-palette:toggle (atom-text-editor.editor)
     -0:03.9 core:confirm (atom-text-editor.editor.mini)
     -0:03.8 php-server:start (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v1.4.4
emmet, v2.3.4
php-server, v0.3.0

# Dev
No dev packages
```

**Comment by leijou** [comment]
Could not replicate. Please update and if the problem still persists provide steps to reproduce.

**Comment by mattwebdev** [comment]
I have the same issue: Atom version 0.2, latest Mac OSX. 

TypeError: path must be a string
  at TypeError (native)
  at fs.lstatSync (fs.js:836:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at Object.module.exports.splitPath (/Users/mheinke/.atom/packages/php-server/lib/php-server.coffee:65:12)
  at Object.module.exports.start (/Users/mheinke/.atom/packages/php-server/lib/php-server.coffee:82:33)
  at atom-workspace.<anonymous> (/Users/mheinke/.atom/packages/php-server/lib/php-server.coffee:38:65)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)
