### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'atom://config'

### ISSUE THREAD

**Issue by petrkott** [leijou/php-server#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.2
**Thrown From**: [php-server](https://github.com/leijou/php-server) package, v0.7.0
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'atom://config'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'atom://config'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.module.exports.splitPath (/Users/kotas/.atom/packages/php-server/lib/php-server.coffee:72:12)
    at Object.module.exports.start (/Users/kotas/.atom/packages/php-server/lib/php-server.coffee:106:33)
    at Object.module.exports.startDocument (/Users/kotas/.atom/packages/php-server/lib/php-server.coffee:67:6)
    at atom-workspace.<anonymous> (/Users/kotas/.atom/packages/php-server/lib/php-server.coffee:48:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -1:36.8.0 application:add-project-folder (div.package-detail.panels-item)
     -1:12.8.0 php-server:start-tree (span.name.icon.icon-file-directory)
  2x -0:56.6.0 core:backspace (atom-text-editor#php-server.startPort.editor.mini.is-focused)
     -0:16.2.0 php-server:start (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.7.0 php-server:start-document (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {},
  "php-server": {
    "overrideErrorlog": true,
    "phpPath": "/usr/local/Cellar/php70/7.0.2/bin/php"
  }
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, v0.18.7
atom-jsx-transform, v0.2.0
autocomplete-php, v0.3.7
minimap, v4.19.0
php-server, v0.7.0
react, v0.12.10

# Dev
No dev packages
```

**Comment by leijou** [comment]
No steps to reproduce, closing
