### ISSUE TITLE
Failed to activate the php-server package

### ISSUE THREAD

**Issue by thespacecadet** [leijou/php-server#15]
hi guys, new to both github and atom, basically after cloning the repo i 
1. put the php-server folder inside packages folder
2.tried to run it.
and got "cant find module 'atom-space-pen-views'

any ideas?

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.7.0

### Stack Trace

Failed to activate the php-server package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.4/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/php-server/lib/php-server-view.coffee:1:13)
    at /packages/php-server/lib/php-server-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/php-server/lib/php-server.coffee:1:17)
    at /packages/php-server/lib/php-server.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
```

### Commands

```
     -0:59.5.0 php-server:start-tree-route (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
php-server 0.7.0 
```

**Comment by Blouet** [comment]
Exactly the same thing happens to me. This application is not easy to figure out and the documentation assumes you know a lot more than I certainly do. Potentially this could be really good but at the moment I am losing the will to live trying to get it to work.

**Comment by leijou** [comment]
This means a dependency was not installed when the plugin was. Installing plugins through atom's config screen is the easiest way and should handle this automatically. If the repo is cloned manually then you will also need to run `npm install` to fetch dependencies
