### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by kapil0000** [leijou/php-server#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.7.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At C:\Users\Kapil\.atom\packages\php-server\lib\php-server.coffee:63

ReferenceError: path is not defined
    at Object.startTreeRoute (/packages/php-server/lib/php-server.coffee:63:12)
    at /packages/php-server/lib/php-server.coffee:47:76)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.20.1/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.20.1/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.20.1/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -0:57.2.0 php-server:start-tree (span.name.icon.icon-file-directory)
     -0:16.8.0 php-server:start-tree-route (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
php-server 0.7.0 
```

**Comment by leijou** [comment]
No steps to reproduce, closing
