### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by BrandAshutosh** [leijou/php-server#26]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: elementary OS
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /home/element/.atom/packages/php-server/lib/php-server.coffee:63

TypeError: Cannot read property 'mainModule' of undefined
    at Object.startTree (/packages/php-server/lib/php-server.coffee:63:55)
    at /packages/php-server/lib/php-server.coffee:51:70)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/opt/atom/resources/app/src/atom-environment.js:1388:34)
    at EventEmitter.outerCallback (/opt/atom/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:48.3.0 php-server:start (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:29.7.0 php-server:start-tree (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text.name.nuclide-file-tree-path)
     -1:21.4.0 atom-live-server:startServer (atom-pane.pane)
     -0:44.5.0 php-cs-fixer:fix (input.hidden-input)
     -0:06.1.0 php-server:start-tree (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory-starred)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.6.0 
atom-live-server 2.2.0 
color-picker 2.2.5 
hyperclick 0.1.5 
intentions 1.1.5 
nuclide 0.269.0 
php-cs-fixer 4.1.1 
php-debug 0.2.5 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-navigation 1.2.1 
php-server 0.8.0 
project-manager 3.3.5 
script 3.17.3 
```

**Comment by leijou** [comment]
No steps to reproduce, closing
