### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop\phplearning\htaccess.txt'

### ISSUE THREAD

**Issue by htuzel** [leijou/php-server#28]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\hayre\Desktop\phplearning\htaccess.txt'

```
At fs.js:902

Error: ENOENT: no such file or directory, lstat 'C:\Users\hayre\Desktop\phplearning\htaccess.txt'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Object.splitPath (/packages/php-server/lib/php-server.coffee:77:12)
    at Object.start (/packages/php-server/lib/php-server.coffee:111:33)
    at Object.startTree (/packages/php-server/lib/php-server.coffee:63:6)
    at /packages/php-server/lib/php-server.coffee:51:70)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/lib/command-palette-view.js:165:35)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.24.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.24.0/resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -1:40.5.0 core:move-left (input.hidden-input)
  8x -1:39.5.0 core:move-right (input.hidden-input)
  5x -1:37.7.0 core:delete (input.hidden-input)
     -1:36.7.0 core:confirm (input.hidden-input)
     -0:52.3.0 intentions:highlight (input.hidden-input)
     -0:52.1.0 command-palette:toggle (input.hidden-input)
  3x -0:48.2.0 core:backspace (input.hidden-input)
  4x -0:46 core:move-down (input.hidden-input)
  4x -0:44 core:backspace (input.hidden-input)
     -0:41.3.0 core:confirm (input.hidden-input)
     -0:41.3.0 php-server:stop (input.hidden-input)
     -0:37.4.0 intentions:highlight (input.hidden-input)
     -0:37.1.0 command-palette:toggle (input.hidden-input)
  3x -0:35.7.0 core:move-down (input.hidden-input)
     -0:34.7.0 core:confirm (input.hidden-input)
     -0:34.7.0 php-server:start-tree (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
color-picker 2.2.5 
css-snippets 1.1.0 
emmet 2.4.3 
file-icons 2.1.16 
hey-pane 1.1.0 
highlight-selected 0.13.1 
Hydrogen 2.2.2 
intentions 1.1.5 
linter 2.0.0 
linter-eslint 8.4.1 
linter-ui-default 1.6.10 
minimap 4.29.7 
php-server 0.8.0 
pigments 0.40.2 
remote-ftp 2.1.4 
```

**Comment by leijou** [comment]
No steps to reproduce, closing
