### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by Peter-Mary** [leijou/php-server#30]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.0 x64
**Electron**: 2.0.18
**OS**: Unknown Windows version
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:941

TypeError: path must be a string or Buffer
    at fs.lstatSync (fs.js:941:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:259:16)
    at Object.splitPath (/packages/php-server/lib/php-server.coffee:77:12)
    at Object.startTreeRoute (/packages/php-server/lib/php-server.coffee:67:25)
    at /packages/php-server/lib/php-server.coffee:52:76)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.35.0/resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.35.0/resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.35.0/resources/app/static/<embedded>:1:696349)
    at EventEmitter.t (~/AppData/Local/atom/app-1.35.0/resources/app/static/<embedded>:1:703816)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:48.5.0 core:copy (input.hidden-input)
     -1:46.1.0 editor:newline (input.hidden-input)
     -1:45.4.0 core:paste (input.hidden-input)
     -1:43 core:cut (input.hidden-input)
     -1:38.1.0 core:copy (input.hidden-input)
     -1:32.5.0 editor:newline (input.hidden-input)
     -1:31.5.0 core:paste (input.hidden-input)
     -1:28.8.0 core:cut (input.hidden-input)
     -1:22.3.0 core:backspace (input.hidden-input)
     -1:20.1.0 core:save (input.hidden-input)
  2x -1:05.0 editor:newline (input.hidden-input)
     -1:00.9.0 core:move-down (input.hidden-input)
     -1:00.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:56.7.0 core:move-right (input.hidden-input)
     -0:54.8.0 core:save (input.hidden-input)
     -0:47.7.0 php-server:start-tree-route (span.name.icon.php-icon.dark-blue)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-terminal 0.8.0 
file-icons 2.1.30 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-jade 0.7.3 
nodejs-snippets 2.0.2 
php-server 0.8.0 
```

**Comment by Peter-Mary** [comment]
Any hint please ?

**Comment by YagaVidal** [comment]
I get the same issue when trying to run php-server from Atom.

Listening on http://127.0.0.1:8080
Document root is E:\Entwicklung\Google Web Designer\WurmDate
PHP Server could not launch
Have you defined the right path to PHP in your settings? Using d:\Entwicklung\PHP

PHP has been properly installed in the above folder.

**Comment by leijou** [comment]
@YagaVidal 
> d:\Entwicklung\PHP
Most likely you want to change your path to  `d:\Entwicklung\PHP\php.exe`
