### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop\template'

### ISSUE THREAD

**Issue by Sarthak-Rout** [leijou/php-server#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\sarthak rout\Desktop\template'

```
At fs.js:941

Error: ENOENT: no such file or directory, lstat 'C:\Users\sarthak rout\Desktop\template'
    at fs.lstatSync (fs.js:941:11)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:259:16)
    at Object.splitPath (/packages/php-server/lib/php-server.coffee:77:12)
    at Object.start (/packages/php-server/lib/php-server.coffee:111:33)
    at Object.startDocument (/packages/php-server/lib/php-server.coffee:72:6)
    at /packages/php-server/lib/php-server.coffee:53:74)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:349922)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:348397)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:718183)
    at EventEmitter.t (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:726106)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -5:27 tree-view:add-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:12.5.0 core:confirm (input.hidden-input)
     -4:48 tree-view:duplicate (span.name.icon.icon-file-text)
     -4:46 core:move-left (input.hidden-input)
     -4:33.7.0 core:confirm (input.hidden-input)
     -4:11.4.0 core:save (input.hidden-input)
     -3:19.5.0 php-server:start (input.hidden-input)
     -2:32.9.0 php-server:start-tree (div.tool-panel.tree-view)
 11x -2:04.8.0 core:backspace (input.hidden-input)
     -1:58.7.0 core:save (input.hidden-input)
     -1:37.1.0 php-server:start-tree (div.tool-panel.tree-view)
     -1:06.8.0 application:reopen-project (div.tool-panel.tree-view)
  2x -0:49.2.0 php-server:start-document (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
php-server 0.8.0 
```

**Comment by leijou** [comment]
No steps to reproduce, closing
