### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Desktop\Атом\index.php'

### ISSUE THREAD

**Issue by acidtick** [leijou/php-server#33]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Unknown Windows version
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Дима\Desktop\Атом\index.php'

```
At fs.js:143

Error: ENOENT: no such file or directory, lstat 'C:\Users\Дима\Desktop\Атом\index.php'
    at fs.lstatSync (fs.js:936:3)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:259:16)
    at Object.splitPath (/packages/php-server/lib/php-server.coffee:77:12)
    at Object.start (/packages/php-server/lib/php-server.coffee:111:33)
    at Object.startTree (/packages/php-server/lib/php-server.coffee:63:6)
    at /packages/php-server/lib/php-server.coffee:51:70)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:744957)
    at EventEmitter.t (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:1:752963)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -1:52.9.0 php-server:start-tree (span.name.icon.icon-file-text)
  3x -1:08.9.0 core:backspace (input.hidden-input)
     -0:57.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:57.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.4.0 php-server:start-tree (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
emmet 2.4.3 
php-server 0.8.0 
```

**Comment by leijou** [comment]
No steps to reproduce, closing
