### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '~/Downloads/sitoWeb/index.html'

### ISSUE THREAD

**Issue by LorenzoMattio** [leijou/php-server#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/lorenzomattio/Downloads/sitoWeb/index.html'

```
At fs.js:115

Error: ENOENT: no such file or directory, lstat '/Users/lorenzomattio/Downloads/sitoWeb/index.html'
    at lstatSync (fs.js:819:3)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:243:27)
    at Object.splitPath (/packages/php-server/lib/php-server.coffee:77:12)
    at Object.start (/packages/php-server/lib/php-server.coffee:111:33)
    at Object.startTree (/packages/php-server/lib/php-server.coffee:63:6)
    at /packages/php-server/lib/php-server.coffee:51:70)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347765)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725136)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733142)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
     -0:08.3.0 php-server:start-tree (span.name.icon.html5-icon)
```

### Non-Core Packages

```
atoms-touchbar 0.4.0 
autocomplete-python 1.16.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.36 
gpp-compiler 3.0.7 
ide-html 0.6.0 
ide-json 0.2.1 
ide-php 0.7.18 
indent-guide-improved 1.4.13 
intentions 1.1.5 
linter 2.3.1 
linter-ui-default 1.8.0 
minimap-linter 2.2.1 
php-server 0.8.0 
platformio-ide-terminal 2.10.0 
pretty-json 2.1.2 
```

**Comment by leijou** [comment]
No steps to reproduce, closing
