### ISSUE TITLE
Uncaught TypeError: The "path" argument must be one of type string, Buffer, or URL. Received type...

### ISSUE THREAD

**Issue by diveyez** [leijou/php-server#39]
**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [php-server](https://github.com/leijou/php-server) package 0.8.0

### Stack Trace

Uncaught TypeError: The "path" argument must be one of type string, Buffer, or URL. Received type object

```
At internal/fs/utils.js:423

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at lstatSync (fs.js:862:3)
    at Object.fs.lstatSync (electron/js2c/asar.js:233:27)
    at Object.splitPath (/packages/php-server/lib/php-server.coffee:77:12)
    at Object.startTreeRoute (/packages/php-server/lib/php-server.coffee:67:25)
    at /packages/php-server/lib/php-server.coffee:52:76)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:349786)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:11:348261)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:765638)
    at EventEmitter.t (~/AppData/Local/atom/app-1.48.0/resources/app/static/<embedded>:1:773644)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
  6x -0:56.3.0 core:move-left (input.hidden-input)
  9x -0:54.4.0 core:move-right (input.hidden-input)
  9x -0:53.3.0 core:move-left (input.hidden-input)
     -0:52.3.0 core:move-right (input.hidden-input)
  2x -0:52 core:move-left (input.hidden-input)
     -0:42.6.0 core:move-right (input.hidden-input)
  4x -0:36.5.0 core:move-left (input.hidden-input)
  4x -0:35.1.0 core:move-right (input.hidden-input)
     -0:34.2.0 core:backspace (input.hidden-input)
     -0:31.3.0 core:save (input.hidden-input)
     -0:29.7.0 core:move-right (input.hidden-input)
     -0:29.4.0 core:backspace (input.hidden-input)
     -0:27.5.0 intentions:highlight (input.hidden-input)
     -0:27.2.0 core:save (input.hidden-input)
     -0:23.1.0 php-server:start-tree (li.file.entry.list-item.selected)
     -0:09.2.0 php-server:start-tree-route (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
aligner-php 1.3.0 
atom-arma-language 0.3.0 
atom-autocomplete-php 0.25.6 
atom-bash 1.1.1 
Atom-Bash-Snippets 0.0.3 
atom-beautify 0.33.4 
atom-browser 1.6.0 
atom-clock 0.1.17 
atom-cursor-indent 0.3.3 
atom-debug-ui 1.0.4 
atom-discord 2.0.2 
atom-ide-ui 0.13.0 
atom-js 1.2.0 
atom-live-server 2.3.0 
atom-live-server-plus 3.0.1 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
auto-indent 0.5.0 
autocomplete-bash-builtins 0.3.5 
bash-bang-syntax 0.3.0 
browser-plus 0.0.98 
build 0.70.0 
build-cmake 0.12.0 
build-cmd 0.5.2 
build-dockerfile 1.0.1 
build-npm-apm 0.12.0 
build-stack 0.3.2 
build-tools 4.5.13 
busy-signal 2.0.1 
dark-core-syntax 2.11.0 
docker 0.8.0 
dockerletion 0.2.0 
drag-drop-text 0.1.4 
drunken-php 0.2.4 
github-plus 1.0.0 
github-search 0.1.0 
github-url-resolver 0.1.1 
go-build 0.2.2 
hey-pane 1.2.0 
html-includes 0.3.0 
html-tab 1.0.2 
html-to-css 0.2.2 
Hydrogen 2.13.1 
hyperclick-php 0.3.0 
ide-bash 1.0.11 
ide-docker 0.1.0 
ide-html 0.6.0 
ide-php 0.7.18 
imdone-atom-github 0.1.11 
indent-detective 0.4.0 
indent-tooltip 0.3.1 
intentions 1.1.5 
kite 0.178.0 
language-arma-atom 2.14.0 
language-arma-atom-mapbuilder 0.4.0 
language-batch 0.4.0 
language-batchfile 0.7.5 
language-docker 1.1.8 
language-ignore 1.8.0 
language-ini 1.23.0 
language-sqf 0.3.0 
linter 2.3.1 
linter-docker 0.3.2 
linter-kubectl 1.0.1 
linter-markdown 5.2.11 
linter-php 1.6.1 
linter-sqf 0.1.2 
local-web-server 0.1.0 
markdown-commander 0.1.1 
markdown-writer 2.11.9 
maya-script-editor-syntax 0.0.3 
npm 2.0.0 
npm-plus 0.4.0 
ocaml-indent 0.7.1 
open-in-sourcetree 0.2.0 
php-composer-completion 0.3.4 
php-cs-fixer 4.1.1 
php-debug 0.3.5 
php-hyperclick 1.2.1 
php-integrator-annotations 1.2.0 
php-integrator-refactoring 1.4.1 
php-light-syntax 1.0.2 
php-server 0.8.0 
php-tools 0.1.0 
platformio-ide-terminal 2.10.0 
pp-markdown 0.0.2 
scroll-through-time 0.3.1 
simple-drag-drop-text 0.5.0 
smart-indent 0.1.0 
swackets 0.35.0 
sync-settings 2.1.0 
teletype 0.13.4 
TerminalColor 1.1.0 
textmate-multimarkdown-syntax 0.1.0 
tool-bar 1.2.0 
tool-bar-markdown-writer 0.5.0 
ue4-tools 0.1.0 
zentabs 0.8.9 
```

**Comment by leijou** [comment]
No steps to reproduce, closing

**Comment by ThorsenRune** [comment]
Atom 1.53. Got this message too and dont know how to get past.
Any solution?
