### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by talomaireeni** [leijou/php-server#5]
**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [php-server](https://github.com/leijou/php-server) package, v0.5.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
packages/php-server/lib/php-server.coffee:60

TypeError: undefined is not a function
    at Object.module.exports.startDocument (packages/php-server/lib/php-server.coffee:91:48)
    at atom-workspace.<anonymous> (packages/php-server/lib/php-server.coffee:64:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
    at jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:150:33)
    at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
    at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
    at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
```
### Commands

```
     -1:43.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-atom-dark-ui)
  3x -0:52.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:42.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:42.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:33.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:28.4.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.8
autocomplete-php, v0.3.6
color-picker, v2.0.11
linter, v1.3.0
linter-php, v1.0.2
php-server, v0.5.0

# Dev
No dev packages
```

**Comment by bweston92** [comment]
+1

**Comment by unional** [comment]
+1

Reproduce by just running php:start from command palette

**Comment by leijou** [comment]
I've updated path calls and added an extra check for when nothing is open in the active pane. Hope that's sorted it for you

**Comment by talomaireeni** [comment]
It is working fine now.
Thanks man.
